### PR TITLE
use less dplyr

### PR DESCRIPTION
**Pull request by aappling-usgs**

### CODE REVIEW

**Comment by lawinslow** [comment]
This title made me lol. You don't see that every day.

**Comment by aappling-usgs** [comment]
getting the same error here that i am with mda.streams - is the JAGS tar.gz file corrupt? is sourceforge failing to supply the full file? is travis failing to access it? what's this `302 Moved Temporarily` note? this comes down to the .travis.yml file on our end, which worked two days ago (https://travis-ci.org/USGS-R/streamMetabolizer/builds/71126896#L641) and has not been touched since then.
```
0.36s$ wget http://downloads.sourceforge.net/project/mcmc-jags/JAGS/3.x/Source/JAGS-3.4.0.tar.gz
--2015-07-17 14:25:39--  http://downloads.sourceforge.net/project/mcmc-jags/JAGS/3.x/Source/JAGS-3.4.0.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 54.192.69.73, 54.240.188.66, 54.192.69.238, ...
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|54.192.69.73|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://downloads.sourceforge.net/#!/project/mcmc-jags/JAGS/3.x/Source/JAGS-3.4.0.tar.gz [following]
--2015-07-17 14:25:39--  http://downloads.sourceforge.net/
Reusing existing connection to downloads.sourceforge.net:80.
HTTP request sent, awaiting response... 200 OK
Length: 639 [text/html]
Saving to: `JAGS-3.4.0.tar.gz'
100%[======================================>] 639         --.-K/s   in 0s      
2015-07-17 14:25:40 (91.1 MB/s) - `JAGS-3.4.0.tar.gz' saved [639/639]
0.06s$ tar xfvs JAGS-3.4.0.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by lawinslow** [comment]
It's sourceforge. Download is different between web browser and wget. Not surprising considering the [dismal state of sourceforge](http://www.i-programmer.info/news/136-open-source/8688-projects-abandon-sourceforge.html) as of late. Download is not large, let's just include it in the package.

**Comment by lawinslow** [comment]
I'm making a PR to add that and update travis build accordingly.

**Pull request merged**
