### PR TITLE
Add jags install for travis

### LINKED ISSUE #48: runjags and rjags installation
On Travis-CI, e.g., https://travis-ci.org/USGS-R/streamMetabolizer/builds/70088636#L1478:
```
* installing *source* package ‘runjags’ ...
** package ‘runjags’ successfully unpacked and MD5 sums checked
checking for prefix by checking for jags... no
configure: error: "Location of JAGS headers not defined. Use configure arg '--with-jags-include' or environment variable 'JAGS_INCLUDE'"
ERROR: configuration failed for package ‘runjags’
* removing ‘/usr/local/lib/R/site-library/runjags’
```
saw similar issues with rjags on Condor before I [temporarily] removed it.

### PR DESCRIPTION
**Pull request by lawinslow**
@aappling-usgs lets see if this fixes #48

### CODE REVIEW

**Comment by lawinslow** [comment]
New error, seems unrelated to jags?

**Comment by aappling-usgs** [comment]
Interesting. Might be unrelated to jags, but it isn't there in the other open PR.
This PR: https://travis-ci.org/USGS-R/streamMetabolizer/builds/70763919#L4729
Other PR: https://travis-ci.org/USGS-R/streamMetabolizer/builds/70762355#L1620

**Comment by aappling-usgs** [comment]
nice! thanks, luke

**Comment by lawinslow** [comment]
Boom. Fixed

**Comment by lawinslow** [comment]
You've got a lot of warnings in there!

**Pull request merged**
