### PR TITLE
function to model solar insolation

### PR DESCRIPTION
**Pull request by aappling-usgs**
ignores day-to-day variability in cloudiness, etc; just the pure seasonal and daily pattern for a given latitude. user sets the maximum daily insolation (default is 1000 W/m2). does this all look right to you, @jread-usgs, code and physics and all?

### CODE REVIEW

**Comment by jread-usgs** [comment]
Looks good. Any testables in there?

**Comment by aappling-usgs** [comment]
There are examples, but good point - should also create official tests. Thing is, what to test - that it runs and produces a vector? Don't know how to test the quality of the output beyond looking at the patterns (ggplot calls in examples) to see if they're sensible. Any ideas?

**Comment by jread-usgs** [comment]
I think there are a number of things that are worth doing there - check when you use the `with.units` arg that you return a valid `unitted` object. Check for nighttime darkness, etc.?

**Comment by aappling-usgs** [comment]
OK, I'll give it a shot. Stay tuned.

**Comment by jread-usgs** [comment]
@aappling-usgs you want to sneak tests in on this PR, or want me to merge this?

**Comment by aappling-usgs** [comment]
yes, i want to sneak tests in. am working on them now.

On Thu, Apr 23, 2015 at 2:10 PM, Jordan S Read <notifications@github.com>
wrote:

> @aappling-usgs <https://github.com/aappling-usgs> you want to sneak tests
> in on this PR, or want me to merge this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/streamMetabolizer/pull/19#issuecomment-95688410>
> .
>



-- 
Alison Appling
Postdoctoral Fellow, USGS Powell Center
USGS Center for Integrated Data Analytics and University of Wisconsin -
Madison
Phone: (608) 821-3927

**Comment by aappling-usgs** [comment]
i think i meant to merge jordan's PR, not this one. oh, well, tests on the way in my next PR

**Pull request merged**
